# Generated by Django 4.2.4 on 2023-08-06 17:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article_categories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categorie', models.CharField(max_length=200, verbose_name='Categorie')),
            ],
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article_header', models.CharField(max_length=200, verbose_name='Header')),
                ('article', models.TextField(verbose_name='Article')),
                ('article_categorie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blogapp.article_categories')),
            ],
        ),
    ]
