# Generated by Django 4.2.4 on 2023-08-15 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0002_post_user_tag_post_meta_post_comment_post_author_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='post',
            field=models.ManyToManyField(to='blogapp.post'),
        ),
    ]
